Repository AdaloHQ/react-multi-menu, pull requests merged in 2022-06, with the labels that each got.

#23 Add purple color to fonts CTA
  src/styles/styles.css
  styles.css
Labels: enhancement

#24 Fix/Remove hover bg and name color for locked option
  src/styles/styles.css
  styles.css
Labels: new free trial

#25 Added gold color for locked hoverConent
  src/index.js
  src/styles/styles.css
  styles.css
Labels: current cycle, new free trial

#26 fix: add background to generic hover content
  src/styles/styles.css
  styles.css
Labels: new free trial

#28 Fix unsafe warning in frontend by using componentDidMount instead of componentWillMount
  src/index.js
Labels: enhancement
